const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nebula', {
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  scanDuplicates: (dir) => ipcRenderer.invoke('scan-duplicates', dir),
  scanLargeFiles: (dir, minSizeMB) => ipcRenderer.invoke('scan-large-files', dir, minSizeMB),
  scanJunk: (dir) => ipcRenderer.invoke('scan-junk', dir),
  scanOldFiles: (dir, months) => ipcRenderer.invoke('scan-old-files', dir, months),
  scanEmptyFolders: (dir) => ipcRenderer.invoke('scan-empty-folders', dir),
  deleteEmptyFolders: (paths) => ipcRenderer.invoke('delete-empty-folders', paths),
  readFilePreview: (filePath) => ipcRenderer.invoke('read-file-preview', filePath),
  exportReport: (data, format) => ipcRenderer.invoke('export-report', data, format),
  moveToBin: (paths) => ipcRenderer.invoke('move-to-bin', paths),
  getBin: () => ipcRenderer.invoke('get-bin'),
  restoreFromBin: (id) => ipcRenderer.invoke('restore-from-bin', id),
  deleteFromBin: (ids) => ipcRenderer.invoke('delete-from-bin', ids),
  getDiskInfo: () => ipcRenderer.invoke('get-disk-info'),
  getDrives: () => ipcRenderer.invoke('get-drives'),
  analyzeSpace: (dir) => ipcRenderer.invoke('analyze-space', dir),
  moveToDrive: (srcPaths, destDir) => ipcRenderer.invoke('move-to-drive', srcPaths, destDir),
  getSchedule: () => ipcRenderer.invoke('get-schedule'),
  setSchedule: (settings) => ipcRenderer.invoke('set-schedule', settings),
  triggerScheduleCheck: () => ipcRenderer.invoke('trigger-schedule-check'),
  onProgress: (cb) => ipcRenderer.on('scan-progress', (_, data) => cb(data)),
  onCopyProgress: (cb) => ipcRenderer.on('copy-progress', (_, data) => cb(data)),
  offCopyProgress: () => ipcRenderer.removeAllListeners('copy-progress'),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
});
